-- Schema usado pela API Prova2024.2.
-- Execute este arquivo conectado ao banco eevee.

CREATE TABLE IF NOT EXISTS times (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS estadios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(160) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS jogadores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(160) NOT NULL,
    data_nascimento DATE NOT NULL,
    posicao VARCHAR(80) NOT NULL,
    time_id INTEGER NOT NULL REFERENCES times(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS jogos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mandante INTEGER NOT NULL REFERENCES times(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    visitante INTEGER NOT NULL REFERENCES times(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    estadio_id INTEGER NOT NULL REFERENCES estadios(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    data_hora TIMESTAMPTZ NOT NULL,
    CONSTRAINT jogos_times_diferentes CHECK (mandante <> visitante),
    CONSTRAINT jogos_estadio_data_hora_unicos UNIQUE (estadio_id, data_hora)
);

CREATE INDEX IF NOT EXISTS jogadores_time_id_idx ON jogadores(time_id);
CREATE INDEX IF NOT EXISTS jogos_mandante_idx ON jogos(mandante);
CREATE INDEX IF NOT EXISTS jogos_visitante_idx ON jogos(visitante);
